"""fisst

Revision ID: 1f78277c0733
Revises: 91090880d564
Create Date: 2022-12-25 23:11:10.972292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f78277c0733'
down_revision = '91090880d564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mon_an',
    sa.Column('mamon', sa.Integer(), nullable=False),
    sa.Column('maloai', sa.String(length=128), nullable=True),
    sa.Column('tenmon', sa.String(length=128), nullable=True),
    sa.Column('anh', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('mamon')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mon_an')
    # ### end Alembic commands ###
