"""fisst

Revision ID: 8b1c6b402512
Revises: 1f78277c0733
Create Date: 2022-12-25 23:14:01.558214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1c6b402512'
down_revision = '1f78277c0733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mon_an', 'loai_mon', ['maloai'], ['maloai'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mon_an', type_='foreignkey')
    # ### end Alembic commands ###
