"""empty message

Revision ID: 94eeaa004d17
Revises: 8b1c6b402512
Create Date: 2022-12-25 23:38:44.503206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94eeaa004d17'
down_revision = '8b1c6b402512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loai_mon',
    sa.Column('maloai', sa.String(length=128), nullable=False),
    sa.Column('tenloai', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('maloai')
    )
    op.create_table('mon_an',
    sa.Column('mamon', sa.String(length=128), nullable=False),
    sa.Column('maloai', sa.String(length=128), nullable=True),
    sa.Column('tenmon', sa.String(length=128), nullable=True),
    sa.Column('anh', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('mamon')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mon_an')
    op.drop_table('loai_mon')
    # ### end Alembic commands ###
