"""fisst

Revision ID: a2b164597f79
Revises: 94eeaa004d17
Create Date: 2022-12-25 23:39:19.166496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b164597f79'
down_revision = '94eeaa004d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mon_an', 'loai_mon', ['maloai'], ['maloai'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mon_an', type_='foreignkey')
    # ### end Alembic commands ###
