"""fisst

Revision ID: dcea03344f32
Revises: d7c4994a421b
Create Date: 2022-12-25 22:43:54.344157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcea03344f32'
down_revision = 'd7c4994a421b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loai_mon',
    sa.Column('maloai', sa.Integer(), nullable=False),
    sa.Column('tenloai', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('maloai')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loai_mon')
    # ### end Alembic commands ###
