"""fisst

Revision ID: ddd077b83b74
Revises: dcea03344f32
Create Date: 2022-12-25 22:47:46.896390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd077b83b74'
down_revision = 'dcea03344f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loai_mon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loai_mon',
    sa.Column('maloai', sa.INTEGER(), nullable=False),
    sa.Column('tenloai', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('maloai')
    )
    # ### end Alembic commands ###
